START_EVENT_NAME = "start"
STOP_EVENT_NAME = "stop"
KILL_EVENT_NAME = "kill"
START_ROUTINE_LOGIC_NAME = "start_routine_logic"
FINISH_ROUTINE_LOGIC_NAME = "finish_routine_logic"
UPDATE_FPS_NAME = "update_fps"
