STOP_EVENT_NAME = "stop"
KILL_EVENT_NAME = "kill"
START_EVENT_NAME = "start"
UPDATE_FPS_NAME = "update_fps"
NOTIFY_ROUTINE_DURATIONS_NAME = "finish_routine_logic"
LOG_DATA = "log_data"
UNLINK = "unlink"
CLEANUP = "cleanup"

INTERNAL_EVENT_NAMES = {LOG_DATA, NOTIFY_ROUTINE_DURATIONS_NAME, UPDATE_FPS_NAME, CLEANUP}
