coverage:
  precision: 0
  status:
    patch:
      default:
        target: 90
      base_pipe:
        target: 90%
        flags:
          - base_pipe
    project:
      default:
        threshold: 1%
      base_pipe:
        target: 90%
        flags:
          - base_pipe
    changes: false

ignore:
  - "demo/"
  - "tests/"
  - "docs/"
  - "pipert2/utils/data_class/"
  - "pipert2/core/base/data_transmitter.py"
  - "pipert2/utils/logging_module_modifiers.py"
  - "pipert2/utils/socketio_logger/"
  - "pipert2/core/handlers/message_handler.py"

flags:
  # filter the folder(s) you wish to measure by that flag
  base_pipe:
    # only include files in the backend folder
    paths:
      - pipert2/